import datetime
import json


def generate_clinical_diagnostic_report(
    patient_id: str,
    signal_type: str,
    diagnosis: str,
    confidence: float,
    probabilities: dict,
    features: dict,
    evaluation_summary: dict = None
) -> str:
    """
    Generates a structured clinical diagnostic report in Markdown format.
    """
    now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report_lines = [
        f"# CLINICAL DIAGNOSTIC & SIGNAL CLASSIFICATION REPORT",
        f"**Generated On:** {now_str} | **Patient ID:** `{patient_id}` | **Signal Modality:** {signal_type.upper()}",
        f"---",
        f"## 1. Primary Diagnostic Impression",
        f"- **Predicted Abnormality / Condition:** `{diagnosis}`",
        f"- **Model Confidence Score:** `{confidence * 100:.2f}%`",
        f"",
        f"### Probability Distribution across Clinical Classes:"
    ]
    
    for cls, prob in probabilities.items():
        bar_len = int(prob * 20)
        bar = "█" * bar_len + "░" * (20 - bar_len)
        report_lines.append(f"- **{cls}**: `{prob * 100:5.2f}%` `[{bar}]`")
        
    report_lines.extend([
        f"",
        f"## 2. Extracted Bio-Signal Physiological Features"
    ])
    
    for k, v in features.items():
        report_lines.append(f"- **{k.replace('_', ' ').title()}**: `{v}`")
        
    if evaluation_summary:
        report_lines.extend([
            f"",
            f"## 3. Deep Learning Model Strict Evaluation Metrics",
            f"- **Overall Accuracy:** `{evaluation_summary.get('accuracy', 'N/A')}`",
            f"- **Balanced Accuracy:** `{evaluation_summary.get('balanced_accuracy', 'N/A')}`",
            f"- **Macro F1-Score:** `{evaluation_summary.get('macro_f1_score', 'N/A')}`",
            f"- **Macro Sensitivity / Recall:** `{evaluation_summary.get('macro_recall_sensitivity', 'N/A')}`",
            f"- **Macro Specificity:** `{evaluation_summary.get('macro_specificity', 'N/A')}`",
            f"- **ROC-AUC Score:** `{evaluation_summary.get('roc_auc_score', 'N/A')}`"
        ])

    report_lines.extend([
        f"",
        f"---",
        f"*Report generated by ECG & EEG Signal Deep Learning Classifier System (PyTorch / SciPy Core Engine).*"
    ])

    return "\n".join(report_lines)
